name: automation-jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EMAIL: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  ui_auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Cypress and dependencies
        run: |
          npm install cypress
          npm install cypress-multi-reporters mocha mochawesome

      - name: Run Cypress tests
        run: |
          npx cypress run --browser chrome --headless --reporter mochawesome

      - name: Create directory for reports
        run: mkdir -p testResults

      - name: Move Cypress report files
        run: mv cypress/reports/mochawesome/*.html testResults/

      - name: Upload report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: CypressHTMLReport
          path: testResults/
