name: automation-jobs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  EMAIL: ${{ secrets.USER }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  ui_auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Cypress and dependencies
        run: |
          npm install cypress
          npm install mochawesome mochawesome-merge mochawesome-report-generator

      - name: Run Cypress tests
        run: |
          npm run cypress:run

      - name: Create directory for reports
        run: mkdir -p cypress/reports/mochawesome/

      - name: Merge Cypress JSON report files
        run: npm run cypress:merge-reports-json

      - name: Merge and create HTML report
        run: |
          npm run cypress:create-html

      - name: Upload JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressJSONReport
          path: /home/runner/work/mantisbt-auto/mantisbt-auto/cypress/reports/mochawesome/report-json.json
          
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressHTMLReport
          path: /home/runner/work/mantisbt-auto/mantisbt-auto/cypress/reports/mochawesome/report-html.html

