jobs:
  ui_auto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Cypress and dependencies
        run: |
          npm install cypress
          npm install mochawesome mochawesome-merge mochawesome-report-generator

      - name: Install mochawesome-report-generator globally
        run: npm install -g mochawesome-report-generator

      - name: Run Cypress tests
        run: |
          npm run cypress:run
        continue-on-error: true

      - name: Create directory for reports
        run: mkdir -p cypress/reports/mochawesome/
        continue-on-error: true

      - name: Merge Cypress JSON report files
        run: npm run cypress:merge-reports-json
        continue-on-error: true

      - name: Generate HTML report
        run: npm run generate-html-report
        continue-on-error: true

      - name: Upload JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressJSONReport
          path: /home/runner/work/mantisbt-auto/mantisbt-auto/cypress/reports/mochawesome/report-json.json
        continue-on-error: true
          
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressHTMLReport
          path: /home/runner/work/mantisbt-auto/mantisbt-auto/cypress/reports/mochawesome
        continue-on-error: true
